<?php

declare(strict_types=1);

namespace behaviorpack\custom\connection;

use behaviorpack\custom\BehaviorPermutableBlock;
use pocketmine\custom\CustomBlockFactory;
use InvalidArgumentException;
use pocketmine\event\Listener;
use pocketmine\event\server\DataPacketSendEvent;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\nbt\tag\ListTag;
use pocketmine\network\mcpe\protocol\StartGamePacket;
use pocketmine\network\mcpe\protocol\types\BlockPaletteEntry;
use pocketmine\network\mcpe\protocol\types\CacheableNbt;
use function count;
use function in_array;
use function is_float;
use function is_int;

/**
 * Adds the block traits of the behavior pack blocks to the block palette
 * of the StartGamePacket, after Customies built it. The states generated by
 * a trait are sent by the trait itself, so they are removed from the
 * properties list.
 */
final class BlockTraitPacketListener implements Listener{

	/** @var list<BlockPaletteEntry>|null */
	private ?array $palette = null;
	private int $sourceCount = -1;

	/**
	 * @priority HIGH
	 */
	public function onDataPacketSend(DataPacketSendEvent $event) : void{
		foreach($event->getPackets() as $packet){
			if(!$packet instanceof StartGamePacket){
				continue;
			}
			if($this->palette === null || $this->sourceCount !== count($packet->blockPalette)){
				$this->sourceCount = count($packet->blockPalette);
				$this->palette = $this->buildPalette($packet->blockPalette);
			}
			$packet->blockPalette = $this->palette;
		}
	}

	/**
	 * @param list<BlockPaletteEntry> $entries
	 * @return list<BlockPaletteEntry>
	 */
	private function buildPalette(array $entries) : array{
		$result = [];
		foreach($entries as $entry){
			$result[] = $this->withTraits($entry);
		}
		return $result;
	}

	private function withTraits(BlockPaletteEntry $entry) : BlockPaletteEntry{
		try{
			$block = CustomBlockFactory::get($entry->getName());
		}catch(InvalidArgumentException){
			return $entry;
		}
		if(!$block instanceof BehaviorPermutableBlock){
			return $entry;
		}
		$traits = $block->getDefinition()["traits"];
		$network = $traits["network"] ?? [];
		if($network === []){
			return $entry;
		}
		$traitStates = $traits["traitStates"] ?? [];
		$root = clone $entry->getStates()->getRoot();
		$properties = $root->getListTag("properties");
		if($properties !== null){
			$kept = [];
			foreach($properties->getValue() as $property){
				if($property instanceof CompoundTag && in_array($property->getString("name", ""), $traitStates, true)){
					continue;
				}
				$kept[] = $property;
			}
			$root->setTag("properties", new ListTag($kept));
		}
		$list = [];
		foreach($network as [$name, $enabledStates, $extra]){
			$list[] = self::traitTag($name, $enabledStates, $extra);
		}
		$root->setTag("traits", new ListTag($list));
		return new BlockPaletteEntry($entry->getName(), new CacheableNbt($root));
	}

	/**
	 * @param list<string>                     $enabledStates
	 * @param array<string, int|float|string> $extra
	 */
	private static function traitTag(string $name, array $enabledStates, array $extra) : CompoundTag{
		$enabled = CompoundTag::create();
		foreach($enabledStates as $state){
			$enabled->setByte($state, 1);
		}
		$tag = CompoundTag::create()
			->setString("name", $name)
			->setTag("enabled_states", $enabled);
		foreach($extra as $key => $value){
			if(is_float($value)){
				$tag->setFloat($key, $value);
			}elseif(is_int($value)){
				$tag->setInt($key, $value);
			}else{
				$tag->setString($key, $value);
			}
		}
		return $tag;
	}
}
